spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/coffeetime?serverTimezone=Asia/Seoul
    password: Hehf9cg77h!@
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
mail:
  address:
    admin: admin@gmail.com
logging:         # (1) 로그 레벨 설정
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
jwt:
  key: ${JWT_SECRET_KEY}               # 민감한 정보는 시스템 환경 변수에서 로드한다.
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420